"""empty message

Revision ID: 7cc136ed13ca
Revises: 271e853b1c24
Create Date: 2023-01-26 16:48:18.251983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc136ed13ca'
down_revision = '271e853b1c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.LargeBinary(length=60),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.LargeBinary(length=60),
               type_=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
